project:
  type: website
  output-dir: docs

website:
  title: "Sampada Pokharel"
  navbar:
    left:
      - href: education.qmd
        text: Education|Coursework
      - href: portfolio.qmd
        text: Work Experience
      - href: techskills.qmd
        text: Skills
    right: 
      - icon: github
        href: https://github.com/sampadapokharel
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/pokharelsampada
        aria-label: LinkedIn
  
  page-footer: 
    left: "Copyright 2022, Sampada Pokharel" 
    right: 
      - icon: github
        href: https://github.com/sampadapokharel/sampadapokharel.github.io

format:
  html:
    theme: theme.scss
    css: styles.css

editor: visual
