project:
  type: website
  output-dir: docs

website:
  title: "Sampada Pokharel"
  navbar:
    left:
      - href: education.qmd
        text: Education|Coursework
      - href: portfolio.qmd
        text: Work Experience
      - href: techskills.qmd
        text: Skills
    right: 
      - icon: github
        href: https://github.com/sampadapokharel
      - icon: linkedin
        href: https://github.com/sampadapokharel

format:
  html:
    theme: theme.scss
    css: styles.css
    toc: true

editor: visual
