project:
  type: website
  output-dir: docs

website:
  title: "Sampada Pokharel"
  navbar:
    left:
      - href: education.qmd
        text: Education|Coursework
      - href: portfolio.qmd
        text: Work Experience
      - href: techskills.qmd
        text: Skills

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual
